import { AppConfig, DevicePreset } from '../types/simulator';

export const DEVICE_PRESETS: DevicePreset[] = [
  {
    id: 'pixel-9-pro',
    name: 'Pixel 9 Pro',
    brand: 'Google',
    width: 412,
    height: 915,
    aspectRatio: '20:9',
    borderRadius: 44,
    punchType: 'center-dot',
    bezelWidth: 12,
  },
  {
    id: 'galaxy-s24-ultra',
    name: 'Galaxy S24 Ultra',
    brand: 'Samsung',
    width: 412,
    height: 919,
    aspectRatio: '19.5:9',
    borderRadius: 28, // S24 Ultra has sharper boxy corners
    punchType: 'center-dot',
    bezelWidth: 10,
  },
  {
    id: 'oneplus-12',
    name: 'OnePlus / Redmi Note',
    brand: 'OnePlus',
    width: 393,
    height: 852,
    aspectRatio: '19.5:9',
    borderRadius: 40,
    punchType: 'center-dot',
    bezelWidth: 12,
  },
  {
    id: 'compact-phone',
    name: 'Compact Android (5.8")',
    brand: 'Android',
    width: 360,
    height: 780,
    aspectRatio: '19.5:9',
    borderRadius: 36,
    punchType: 'center-dot',
    bezelWidth: 12,
  },
  {
    id: 'pixel-tablet',
    name: 'Android Tablet / Fold',
    brand: 'Google',
    width: 768,
    height: 1024,
    aspectRatio: '4:3',
    borderRadius: 32,
    punchType: 'pill',
    bezelWidth: 18,
  },
];

export const INITIAL_APPS: AppConfig[] = [
  {
    id: 'user-app',
    name: 'User App',
    subtitle: 'Buyer & Consumer Marketplace',
    role: 'Buyer / Consumer',
    url: 'http://localhost:8083',
    defaultPort: 8083,
    accentColor: '#f59e0b',
    badgeBg: 'bg-amber-500/10 text-amber-400 border-amber-500/30',
    badgeBorder: 'border-amber-500/40',
    glowClass: 'shadow-device-glow-user',
    status: 'checking',
    deviceId: 'pixel-9-pro',
    orientation: 'portrait',
  },
  {
    id: 'farmer-app',
    name: 'Farmer App',
    subtitle: 'Produce Listing & Verification',
    role: 'Farmer / Producer',
    url: 'http://localhost:8082',
    defaultPort: 8082,
    accentColor: '#10b981',
    badgeBg: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/30',
    badgeBorder: 'border-emerald-500/40',
    glowClass: 'shadow-device-glow-farmer',
    status: 'checking',
    deviceId: 'pixel-9-pro',
    orientation: 'portrait',
  },
  {
    id: 'logistic-app',
    name: 'Logistics Partner App',
    subtitle: 'Trip Dispatch & Route Tracking',
    role: 'Delivery Partner',
    url: 'http://localhost:8081',
    defaultPort: 8081,
    accentColor: '#3b82f6',
    badgeBg: 'bg-blue-500/10 text-blue-400 border-blue-500/30',
    badgeBorder: 'border-blue-500/40',
    glowClass: 'shadow-device-glow',
    status: 'checking',
    deviceId: 'pixel-9-pro',
    orientation: 'portrait',
  },
];

export const BACKEND_SERVICES = [
  { id: 'farmer-api', name: 'Farmer API', port: 4000, healthUrl: 'http://localhost:4000/api/v1/health' },
  { id: 'user-api', name: 'User API', port: 4001, healthUrl: 'http://localhost:4001/api/v1/health' },
  { id: 'logistic-api', name: 'Logistic API', port: 4002, healthUrl: 'http://localhost:4002/api/v1/health' },
  { id: 'admin-api', name: 'Admin API', port: 4003, healthUrl: 'http://localhost:4003/api/v1/health' },
];
